application:
  bindAddress: :8453
  production: false
  debug: false
database:
  address: event-db:3306
  name: event
  username: admin
  password: admin
authentication:
  authority: https://algotiqa-server:8443/auth/realms/algotiqa
messaging:
  address : rabbitmq:5672
  username: admin
  password: admin
  journal:
    directory      : journal
    queueSize      : 1000
    compactMessages: 1000
    dbSpoolInterval: 0
